<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CodeIgniter Application Test Suite" tests="3" assertions="3" errors="0" failures="0" skipped="0" time="3.175008">
    <testsuite name="Privilege_test" file="C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php" tests="3" assertions="3" errors="0" failures="0" skipped="0" time="3.175008">
      <testcase name="test_get_roles" class="Privilege_test" classname="Privilege_test" file="C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php" line="12" assertions="1" time="1.063872">
        <system-out>
A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: HTTP_HOST
Filename:    C:\xampp\htdocs\document_management_system\application\config\config.php
Line Number: 26

Backtrace:
	File: C:\xampp\htdocs\document_management_system\application\config\config.php
	Line: 26
	Function: _error_handler

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 323
	Function: require

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 111
	Function: __construct

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 111
	Function: __construct

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\functions.php
	Line: 57
	Function: load_class

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php
	Line: 79
	Function: reset_instance

	File: C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php
	Line: 6
	Function: resetInstance

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 896
	Function: setUp

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestResult.php
	Line: 694
	Function: runBare

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 855
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 733
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 733
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/TestRunner.php
	Line: 526
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php
	Line: 209
	Function: doRun

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php
	Line: 140
	Function: run

	File: C:\bin\phpunit.phar
	Line: 546
	Function: main


</system-out>
      </testcase>
      <testcase name="test_get_privilege_of_general_role" class="Privilege_test" classname="Privilege_test" file="C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php" line="17" assertions="1" time="1.055273">
        <system-out>
A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: HTTP_HOST
Filename:    C:\xampp\htdocs\document_management_system\application\config\config.php
Line Number: 26

Backtrace:
	File: C:\xampp\htdocs\document_management_system\application\config\config.php
	Line: 26
	Function: _error_handler

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 323
	Function: require

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 111
	Function: __construct

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 111
	Function: __construct

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\functions.php
	Line: 57
	Function: load_class

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php
	Line: 79
	Function: reset_instance

	File: C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php
	Line: 6
	Function: resetInstance

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 896
	Function: setUp

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestResult.php
	Line: 694
	Function: runBare

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 855
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 733
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 733
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/TestRunner.php
	Line: 526
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php
	Line: 209
	Function: doRun

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php
	Line: 140
	Function: run

	File: C:\bin\phpunit.phar
	Line: 546
	Function: main


</system-out>
      </testcase>
      <testcase name="test_get_privilege_details" class="Privilege_test" classname="Privilege_test" file="C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php" line="21" assertions="1" time="1.055863">
        <system-out>
A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: HTTP_HOST
Filename:    C:\xampp\htdocs\document_management_system\application\config\config.php
Line Number: 26

Backtrace:
	File: C:\xampp\htdocs\document_management_system\application\config\config.php
	Line: 26
	Function: _error_handler

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 323
	Function: require

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 111
	Function: __construct

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\replacing\core\Common.php
	Line: 111
	Function: __construct

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\functions.php
	Line: 57
	Function: load_class

	File: C:\xampp\htdocs\document_management_system\application\tests\_ci_phpunit_test\CIPHPUnitTestCase.php
	Line: 79
	Function: reset_instance

	File: C:\xampp\htdocs\document_management_system\application\tests\models\Privilege_test.php
	Line: 6
	Function: resetInstance

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 896
	Function: setUp

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestResult.php
	Line: 694
	Function: runBare

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestCase.php
	Line: 855
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 733
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/Framework/TestSuite.php
	Line: 733
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/TestRunner.php
	Line: 526
	Function: run

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php
	Line: 209
	Function: doRun

	File: phar://C:/bin/phpunit.phar/phpunit/TextUI/Command.php
	Line: 140
	Function: run

	File: C:\bin\phpunit.phar
	Line: 546
	Function: main


</system-out>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
